CREATE TABLE products
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY,
    ean      VARCHAR(10)  NOT NULL,
    name     VARCHAR(255) NOT NULL,
    price    NUMERIC(19, 2) NOT NULL,
    quantity INTEGER      NOT NULL,

    CONSTRAINT pk_products
        PRIMARY KEY (id),

    CONSTRAINT uk_products_ean
        UNIQUE (ean),

    CONSTRAINT chk_products_ean_format
        CHECK (ean ~ '^[0-9]{10}$'),

    CONSTRAINT chk_products_name_not_blank
        CHECK (btrim(name) <> ''),

    CONSTRAINT chk_products_price_positive
        CHECK (price > 0),

    CONSTRAINT chk_products_quantity_non_negative
        CHECK (quantity >= 0)
);